apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: evict-pod
spec:
  version: {{ .TagName }}
  homepage: https://github.com/rajatjindal/kubectl-evict-pod
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: {{addURIAndSha "https://github.com/rajatjindal/kubectl-evict-pod/releases/download/{{ .TagName }}/darwin-amd64-{{ .TagName }}.tar.gz" .TagName }}
    bin: kubectl-evict-pod
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-evict-pod/releases/download/{{ .TagName }}/linux-amd64-{{ .TagName }}.tar.gz" .TagName }}
    bin: kubectl-evict-pod
  shortDescription: Evicts the given pod
  description: |
    Usage:
      kubectl evict-pod <pod-name> -n <namespace-name>
      This plugin evicts the given pod. This is particularly useful for testing pod disruption budget rules.
      Read more documentation at: https://github.com/rajatjindal/kubectl-evict-pod